sequenceDiagram
  participant A
  participant B
  A<<->>B: Duplex async
  A<<-->>B: Duplex async dotted
  A->>B: Async
  A-->>B: Async dotted
  A->B: Solid
  A-->B: Dotted
  A-x B: Cross
  A--x B: Cross dotted
  A-) B: Open
  A--) B: Open dotted

