---
config:
  themeVariables:
    nodeBkg: "#FFEEDD"
    nodeBorder: "#8844AA"
    nodeTextColor: "#112233"
    lineColor: "#222222"
    arrowheadColor: "#222222"
    clusterBkg: "#FFFBE6"
    clusterBorder: "#AAAA33"
    fontFamily: "Trebuchet MS"
    fontSize: "15px"
---
flowchart TD
  subgraph Group
    A[Alpha] --> B[Beta]
  end
  B --> C{Gamma}

