flowchart TD
    A{end of stdout}
    B[subgraph data]
    C((flowchart style))
    D[/graph direction/]
    E{Is class defined?}
    F[style properties]
    G{click handler}

    A --> B
    B --> C
    C --> D
    D --> E
    E --> F
    F --> G
