---
config:
  pie:
    textPosition: 0.58
  themeVariables:
    pieOuterStrokeWidth: "3px"
    pieSectionTextColor: "#333333"
    pieTitleTextColor: "#111111"
    pieSectionTextSize: "13px"
    pieTitleTextSize: "18px"
    pie1: "#00AAFF"
    pie2: "#FFAA00"
---
pie showData
  title Themed Pets
  "Dogs" : 30
  "Cats" : 15
  "Rats" : 5

