flowchart LR
  A@{ shape: rect, label: "Rect" }
  B@{ shape: rounded, label: "Rounded" }
  C@{ shape: stadium, label: "Stadium" }
  D@{ shape: subroutine, label: "Subroutine" }
  E@{ shape: circle, label: "Circle" }
  F@{ shape: cylinder, label: "Cylinder" }
  G@{ shape: diamond, label: "Decision" }
  H@{ shape: hexagon, label: "Hexagon" }
  I@{ shape: parallelogram, label: "Para" }
  J@{ shape: trapezoid, label: "Trap" }
  K@{ shape: trapezoidAlt, label: "TrapAlt" }
  L@{ shape: "lean-l", label: "LeanL" }
  M@{ shape: "lean-r", label: "LeanR" }
  A --> B --> C --> D --> E --> F --> G --> H --> I --> J --> K --> L --> M

